name: frontier_basic
description: Basic authentication and authorization strategies for the Frontier package.
version: 1.0.1
repository: https://github.com/avesbox/frontier
homepage: https://frontier.avesbox.com
topics: 
  - authentication
  - authorization
  - backend
  - basic
  - http

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  frontier_strategy: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
