name: frontier_shelf
description: A Shelf adapter for Frontier. It allows you to use Frontier with Shelf.
version: 1.0.0
repository: https://github.com/avesbox/frontier
homepage: https://frontier.avesbox.com
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  frontier: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
