name: frontier_shelf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  frontier: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
