name: frontier_strategy
description: Utility package to create strategies usable by the Frontier package.
version: 0.0.2
repository: https://github.com/avesbox/frontier
topics: 
  - authentication
  - authorization
  - backend
  - web
  - http

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
