name: frontier_strategy
description: Utility package to create strategies usable by the Frontier package.
version: 0.0.1
repository: https://github.com/serinus-nest/frontier
topics: 
  - authentication
  - authorization
  - backend
  - web
  - http

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
