name: frontier
description: Create your own authentication and authorization strategies for your web application.
version: 1.0.0
repository: https://github.com/avesbox/frontier
topics: 
  - authentication
  - authorization
  - backend
  - web
  - http

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  frontier_strategy: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
