name: frontier_openid
description: OpenID Connect authentication and authorization strategies for the Frontier package.
version: 1.0.0
repository: https://github.com/avesbox/frontier
homepage: https://frontier.avesbox.com
topics: 
  - authentication
  - authorization
  - backend
  - openid
  - http

# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.5.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  openid_client: ^0.4.9
  frontier_strategy: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
