name: frontier_jwt
description: Strategy for Frontier that uses JWT for authentication.
version: 1.0.0
repository: https://github.com/avesbox/frontier
topics: 
  - authentication
  - authorization
  - backend
  - jwt
  - http

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.1
  frontier_strategy: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
